services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/temperature_service
    depends_on:
      - postgres

  postgres:
    image: timescale/timescaledb:latest-pg16
    container_name: timescaledb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: temperature_service
      PGTZ: UTC
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
