apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: iotsimulator
  name: iotsimulator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iotsimulator
  template:
    metadata:
      labels:
        app: iotsimulator
    spec:
      containers:
      - name: temperature-service
        image: localhost:5555/temperature-service:latest
        envFrom:
        - configMapRef:
            name: iotsimulator-env
        - secretRef:
            name: iotsimulator-secret
        resources: {}
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10

      - name: dataproducer
        image: localhost:5555/temperature-service:latest
        command: ["/bin/sh", "-c"]
        args:
          - |
            echo "Waiting for temperature-service to be ready..."
            until curl -s http://localhost:8000/health; do
              echo "temperature-service is not ready yet. Waiting..."
              sleep 2
            done
            echo "temperature-service is ready. Starting dataproducer..."
            python -m app.simulation.runner
        envFrom:
        - configMapRef:
            name: iotsimulator-env
        resources: {}
