apiVersion: v1
kind: Service
metadata:
  name: iotsimulator-service
  labels:
    app: iotsimulator
spec:
  type: NodePort
  selector:
    app: iotsimulator
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080
